### PR TITLE
Feature/hw04 dark theme

### PR DESCRIPTION
**Pull request by jeffsmithepic**
Addresses #72 

Acceptance Criteria: Adds a toggle slider to the Settings tab that allows users to change the UI theme throughout the app to a dark theme.

Testing:
1. Navigate to Settings
2. Toggle the `Dark Mode` slider under `General Settings`
3. Verify screen changes to a dark theme
4. Verify all UI throughout the app is in a dark theme (excluding any WIP pages such as Notification Settings, Friends, etc)

Additional notes:
All the colors used for each theme are defined in theme/themes.js

Screenshots:
image
image
image

### CODE REVIEW

**Comment by MeronDT** [comment]
People Page has white background still, but it hasn't been implemented on this branch I think should be good as long as we update it once we push Garvin's changes to main.

LGTM on ios

**Comment by jeffsmithepic** [comment]
Yeah I'll get on resolving the merge conflicts rn

**Comment by jeffsmithepic** [comment]
quick update:
- Merged with main as of 12/4, adding theme for the new pages
- added async storage so the dark theme setting persists even if you close the app and re login
- applied dark/light theme to the sign in page
- added basic title that says "StudyMeets" to the sign in page

**Comment by jeffsmithepic** [comment]
working on merge conflicts

**Pull request merged**
