### PR TITLE
Password Visibility

### PR DESCRIPTION
**Pull request by djoyneruscb**
Created a button to toggle On & off password visibility.

### CODE REVIEW

**Review by tim-choi — APPROVED** [review]
LGTM

**Review by GarvinYoung — CHANGES_REQUESTED** [review]
Small changes to be more in-line with traditional login pages.
- default should be hidden password
- have the button change between show/hide or implement the eye with a slash through it if you feel like it

**Comment by MeronDT** [comment]
LGTM

**Review by GarvinYoung — APPROVED** [review]
lgtm

**Comment by miguel-luis9** [comment]
LGTM!

**Pull request merged**
