### PR TITLE
Set Meeting date and time for a StudyMeet

### PR DESCRIPTION
**Pull request by tim-choi**
I also fixed UI to be consistent across all the components and when the CreateStudyMeet modal is open, the explore buttons don't work. 

Todo: When the CreateStudyMeet modal is closed, the fields should all be reset. Also editPost needs to have the datetime picker implemented for it as well.

IMG_3833
IMG_3834
IMG_3835
IMG_3836
IMG_3837

### CODE REVIEW

**Comment by jeffsmithepic** [comment]
I get this error when trying to build this branch.

```
Android Bundling failed 5889ms C:\Users\chiba\Desktop\Projects\school\cs184\team08-StudyMeets-1\StudyMeets\node_modules\expo\AppEntry.js (2853 modules)
Unable to resolve "@react-native-community/datetimepicker" from "app\screens\CreateNewPost.js"
```

did you `git add` the package-lock and package.json's after doing `npm install @react-native-community/datetimepicker`?

**Comment by MeronDT** [comment]
LGTM on ios

Not sure if intended but user can set next meeting to date/time that have already past

**Review by MeronDT — APPROVED** [review]
LGTM on ios

Not sure if intended but user can set next meeting to date/time that have already past

**Review by GarvinYoung — APPROVED** [review]
lgtm on android

**Pull request merged**
